# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160101_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Theme'),
        ),
    ]
