# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160105_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='personal',
            field=models.BooleanField(default=False),
        ),
    ]
