# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_entry_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='section_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='order',
            field=models.IntegerField(default=99999),
        ),
    ]
