# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160119_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='section_name',
        ),
    ]
