# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_entry_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='recurrence_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
